//
// Created by Maarten Van Loo on 8/10/2022.
//

#ifndef I_COMPUTERGRAPHICS_INTERSECTION_H
#define I_COMPUTERGRAPHICS_INTERSECTION_H

namespace MRay {

}


#endif //I_COMPUTERGRAPHICS_INTERSECTION_H
